- name: Copy file configuration
  template:
    src: template.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660

- name: Restart service
  service:
    name: elasticsearch
    state: restarted