---
# tasks file for roles/elasticsearch
- block:
    - import_tasks: prerequisite.yml
    - import_tasks: config_repo.yml
    - import_tasks: install_packages.yml
    - import_tasks: config_firewall.yml
    - import_tasks: config_elasticsearch.yml
    
    - name: Wait 1.30 minute
      wait_for:
        timeout: 90
    
    - name: Check elasticsearch
      uri:
        url: "http://{{ ansible_facts.default_ipv4.address }}:9200"
        return_content: yes
      register: this

#? IF failed becuase elasticsearch.service not start 
#? remove /var/lib/elasticsearch -> reinstall

    - name: Show result
      debug: 
        var: this
        
  rescue:
    - debug:
        msg: "Installation Error!!!. Please install manually."
