- name: Allocate sufficient file descriptors per process
  blockinfile:
    path: /etc/security/limits.conf
    block: |
      * soft nofile 65536
      * hard nofile 65536 

- name: Allocate sufficient threads per user
  blockinfile:
    path: /etc/security/limits.conf
    block: |
      * soft nproc 4096
      * hard nproc 4096  

- name: Disable swapping
  replace:
    path: /etc/fstab
    regexp: '(^UUID.*\w\d\sswap)'
    replace: '#\1'