---
- name: Create playbook template
  hosts: localhost
  gather_facts: false
  vars_prompt:

    - name: Name
      prompt: "What is the name of playbook?"
      private: no

    - name: Title
      prompt: "What is the title of playbook?"
      private: no

    - name: Host
      prompt: "Which host to defined in playbook?"
      private: no

  tasks:

    - name: Create template
      copy:
        content:
          "---
          \n- name: {{ Title }}
          \n  hosts: {{ Host }}
          \n  tasks:
          \n    - name:"
        dest: ./playbook/{{ Name }}.yml




