- name: Start firewall services
  service:
    name: firewalld
    state: started
    enabled: true

- name: Start redis services
  service:
    name: redis
    state: started
    enabled: true

- name: Allow redis service on firewall
  firewalld:
    service: redis
    immediate: true
    permanent: true
    state: enabled
