- name: Update packages
  dnf:
    name: "*"
    state: latest

- name: Install redis 
  dnf:
    name: redis
    state: latest
  
- name: Install firewalld
  dnf:
    name: firewalld
    state: latest
