---
# tasks file for roles/redis
- block:
    - import_tasks: install_packages.yml
    - import_tasks: config_firewall.yml
    - import_tasks: check.yml
    - import_tasks: config_redis.yml

  rescue:
    - name: Failure
      debug:
        msg: "Installation failed. Please install manually"
