--- 
- name: Implementing Playbooks 
  hosts: ubuntu2
  tasks:

    - name: Latest versions of packages
      apt:
        name:
          - firewalld
          - apache2
          - php
          - php-mysql
          - mariadb-server
         
        state: latest
    
    - name: Ensure firewalld service is enabled and started
      service:
        name: firewalld
        enabled: true
        state: started

    - name: Ensure firewalld permits service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: Ensure httpd service is enabled and started
      service:
        name: apache2
        enabled: true
        state: started

    - name: Ensure mariadb service is enabled and started
      service:
        name: mariadb
        enabled: true
        state: started

- name: Test
  hosts: localhost
  become: false
  tasks:
    - name: test
      uri:
        url: http://192.168.93.131
        return_content: true
        status_code: 200
