---
- name: Install packages
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: install packages
      dnf:
        name:
          - firewalld
          - httpd
          - php
          - php-mysqlnd
          - mariadb-server
        state: latest

    - name: Ensure firewalld is enabled and started
      service:
        name: firewalld
        enabled: true
        state: started

    - name: Ensure firewalld is permit
      firewalld:
        service: http
        permanent: true
        state: enabled

    - name: Ensure httpd is enabled and started
      service:
        name: httpd
        enabled: true  
        state: started  
