---
- name: test facts
  hosts: test
  #gather_facts: false
  tasks:
    # - debug:
    #     var: ansible_default_ipv4.address
    # - shell: whoami
    #   register: this
    # - debug: var=this.stdout

    # - name: test template
    #   template:
    #     src: ./template.j2
    #     dest: /tmp/test.yml
    #     owner: root
    #     group: elasticsearch
    #     mode: 0660
    #    owner: tinnawat
    #    group: tinnawat
      #delegate_to: localhost
      - name: test
        shell: whoami
        register: this

      - name: Show result
        debug:
          var: this.stdout
    